RushHour/Controllers/ActivityController.cs
using DataAccess.Models;
using Repositories;
using RushHour.Helpers;
using RushHour.ViewModels;
using Services;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RushHour.Controllers
{
    [CustomAuthorize(AccessRightsInput = "001")]
    public class ActivityController : Controller
    {
        #region Constructors and fields
        private ActivityService activityService;
        public ActivityController()
        {
            UnitOfWork unitOfWork = new UnitOfWork();
            this.activityService = new ActivityService(new ModelStateWrapper(this.ModelState), unitOfWork.ActivityRepository, unitOfWork);
        }
        #endregion

        public ActionResult Create()
        {
            ActivityViewModel createActivityViewModel = new ActivityViewModel();
            return View(createActivityViewModel);
        }

        [HttpPost]
        public ActionResult Create(ActivityViewModel createActivityViewModel)
        {
            if (activityService.PreValidate())
            {
                Activity activityInput = new Activity();
                activityInput.Name = createActivityViewModel.Name;
                activityInput.Duration = createActivityViewModel.Duration;
                activityInput.Price = createActivityViewModel.Price;
                if (activityService.Save(activityInput))
                {
                    TempData["Message"] = "Activity saved successfully!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Ooops something went wrong";
                }
                return RedirectToAction("GetAll");
            }
            return View();
        }

        public ActionResult GetAll()
        {
            List<Activity> activitiesDb = activityService.GetAll();
            List<ActivityViewModel> activitiesViewModel = new List<ActivityViewModel>();
            foreach (Activity item in activitiesDb)
            {
                activitiesViewModel.Add(
                    new ActivityViewModel
                    {
                        Id = item.Id,
                        Duration = item.Duration,
                        Name = item.Name,
                        Price = item.Price
                    });
            }
            return View(activitiesViewModel);
        }

        public ActionResult Edit(int id)
        {
            Activity activityDb = activityService.GetAll(activity => activity.Id == id).FirstOrDefault();
            ActivityViewModel editActivityViewModel = new ActivityViewModel();
            editActivityViewModel.Id = activityDb.Id;
            editActivityViewModel.Name = activityDb.Name;
            editActivityViewModel.Price = activityDb.Price;
            editActivityViewModel.Duration = activityDb.Duration;
            return View(editActivityViewModel);
        }

        [HttpPost]
        public ActionResult Edit(ActivityViewModel editActivityViewModel)
        {
            if (activityService.PreValidate())
            {
                Activity activityInput = new Activity();
                activityInput.Id = editActivityViewModel.Id;
                activityInput.Name = editActivityViewModel.Name;
                activityInput.Duration = editActivityViewModel.Duration;
                activityInput.Price = editActivityViewModel.Price;
                if (activityService.Save(activityInput))
                {
                    TempData["Message"] = "Activity saved successfully!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Ooops something went wrong";
                }
                return RedirectToAction("GetAll");
            }
            return View();
        }

        public ActionResult Delete(int id)
        {
            if (activityService.DeleteById(id))
            {
                TempData["Message"] = "Activity deleted successfully!";
            }
            else
            {
                TempData["ErrorMessage"] = "Ooops something went wrong";
            }
            return RedirectToAction("GetAll");
        }
    }
}

RushHour/Controllers/AppointmentController.cs
using DataAccess.Models;
using Repositories;
using RushHour.Helpers;
using RushHour.ViewModels;
using Services;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace RushHour.Controllers
{
    [CustomAuthorize(AccessRightsInput = "011")]
    public class AppointmentController : Controller
    {
        #region Constructors and fields
        private AppointmentService appointmentService;
        private UserService userService;
        private ActivityService activityService;
        public AppointmentController()
        {
            UnitOfWork unitOfWork = new UnitOfWork();
            this.appointmentService = new AppointmentService(new ModelStateWrapper(this.ModelState), unitOfWork.AppointmentRepository, unitOfWork);
            this.userService = new UserService(new ModelStateWrapper(this.ModelState), unitOfWork.UserRepository, unitOfWork);
            this.activityService = new ActivityService(new ModelStateWrapper(this.ModelState), unitOfWork.ActivityRepository, unitOfWork);
        }
        #endregion

        public ActionResult Create()
        {
            AppointmentViewModel createAppointmentViewModel = new AppointmentViewModel();
            if (TempData["currentAppointment"] != null)
            {
                Appointment currentAppointment = (Appointment)TempData["currentAppointment"];
                createAppointmentViewModel.Id = currentAppointment.Id;
                createAppointmentViewModel.StartDateTime = Convert.ToString(currentAppointment.StartDateTime);
                createAppointmentViewModel.EndDateTime = Convert.ToString(currentAppointment.EndDateTime);
                createAppointmentViewModel.currentAppointmentActivities = currentAppointment.Activities;
                createAppointmentViewModel.UserId = currentAppointment.UserId;
                createAppointmentViewModel.IsCancelled = currentAppointment.IsCancelled;
            }
            return View(createAppointmentViewModel);
        }

        [HttpPost]
        public ActionResult Create(AppointmentViewModel createAppointmentViewModel)
        {
            if (createAppointmentViewModel.IsCancelled && createAppointmentViewModel.Id != 0)
            {
                ModelState.AddModelError("", "Cannot edit an cancelled appointment");
            }

            if (appointmentService.PreValidate())
            {
                Appointment appointmentInput = new Appointment();
                bool isEdit = false;
                if (createAppointmentViewModel.Id != 0)
                {
                    appointmentInput.Id = createAppointmentViewModel.Id;
                    appointmentInput = appointmentService.GetAll(x => x.Id == createAppointmentViewModel.Id).FirstOrDefault();
                    isEdit = true;
                }
                else
                {
                    appointmentInput.UserId = LoginUserSession.Current.UserId;
                }

                appointmentInput.StartDateTime = DateTime.ParseExact(createAppointmentViewModel.StartDateTime, "dd/MM/yyyy HH:mm", null);
                List<Activity> chosenActivities = new List<Activity>();
                foreach (int activityId in createAppointmentViewModel.chosenActivitiesIds)
                {
                    chosenActivities.Add(activityService.GetAll(x => x.Id == activityId).FirstOrDefault());
                }
                appointmentInput.EndDateTime = appointmentService.CalculateEndDateTime(appointmentInput.StartDateTime, chosenActivities);
                if (!appointmentService.TakenDateTimeCheck(appointmentInput.StartDateTime, appointmentInput.EndDateTime, isEdit, appointmentInput.UserId)) //if current time is taken
                {
                    return View(createAppointmentViewModel);
                }
                appointmentInput.Activities.Clear();
                appointmentInput.Activities.AddRange(chosenActivities);
                if (appointmentService.Save(appointmentInput))
                {
                    TempData["Message"] = "Appointment saved successfully!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Ooops something went wrong";
                }
                return RedirectToAction("GetAll");
            }
            return View(createAppointmentViewModel);
        }

        public ActionResult GetAll()
        {
            Func<DataAccess.Models.Appointment, bool> filter;
            if (!LoginUserSession.Current.IsAdmin)
            {
                filter = delegate (DataAccess.Models.Appointment appointment)
                {
                    if (appointment.UserId == LoginUserSession.Current.UserId)
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                };
            }
            else
            {
                filter = null;
            }
            List<Appointment> appointmentsDb = new List<Appointment>();
            appointmentsDb = appointmentService.GetAll(filter);
            List<AppointmentViewModel> appointmetsViewModel = new List<AppointmentViewModel>();

            foreach (Appointment appointment in appointmentsDb)
            {
                appointmetsViewModel.Add(new AppointmentViewModel
                {
                    Id = appointment.Id,
                    UserId = appointment.UserId,
                    UserEmail = userService.GetAll(x => x.Id == appointment.UserId).FirstOrDefault().Email,
                    StartDateTime = Convert.ToString(appointment.StartDateTime),
                    EndDateTime = Convert.ToString(appointment.EndDateTime),
                    IsCancelled = appointment.IsCancelled
                });
            }

            return View(appointmetsViewModel);
        }

        public ActionResult Edit(int id)
        {
            Appointment currentAppointment = appointmentService.GetAll(x => x.Id == id).FirstOrDefault();
            TempData["currentAppointment"] = currentAppointment;
            return RedirectToAction("Create");
        }

        [CustomAuthorize(AccessRightsInput = "001")]
        public ActionResult Delete(int id)
        {
            if (appointmentService.DeleteById(id))
            {
                TempData["Message"] = "Appointment deleted successfully!";
            }
            else
            {
                TempData["ErrorMessage"] = "Ooops something went wrong";
            }
            return RedirectToAction("GetAll");
        }

        public ActionResult Cancel(int id)
        {
            Appointment appointmentDb = appointmentService.GetAll(x => x.Id == id).FirstOrDefault();
            appointmentDb.IsCancelled = true;
            if (appointmentService.Save(appointmentDb))
            {
                TempData["Message"] = "Appointment cancelled successfully!";
            }
            else
            {
                TempData["ErrorMessage"] = "Ooops something went wrong";
            }
            return RedirectToAction("GetAll");
        }
    }
}

RushHour/Controllers/UserController.cs
using DataAccess.Models;
using Repositories;
using RushHour.Helpers;
using RushHour.ViewModels;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RushHour.Controllers
{
    public class UserController : Controller
    {
        #region Constructors and fields
        private UserService userService;
        public UserController()
        {
            UnitOfWork unitOfWork = new UnitOfWork();
            this.userService = new UserService(new ModelStateWrapper(this.ModelState), unitOfWork.UserRepository, unitOfWork);
        }
        #endregion

        [CustomAuthorize(AccessRightsInput = "101")]
        public ActionResult Register()
        {
            return View();
        }

        [CustomAuthorize(AccessRightsInput = "101")]
        [HttpPost]
        public ActionResult Register(RegisterUserViewModel registerViewModel)
        {
            User userInput = new DataAccess.Models.User();
            userInput.Name = registerViewModel.Name;
            userInput.Password = registerViewModel.Password;
            userInput.IsAdmin = false;
            userInput.Email = registerViewModel.Email;
            userInput.Phone = registerViewModel.Phone;
            if (!userService.ValidateUser(userInput))
            {
                return View(registerViewModel);
            }

            if (userService.Save(userInput))
            {
                TempData["Message"] = "Registered successfully!";
            }
            else
            {
                TempData["ErrorMessage"] = "Ooops something went wrong";
            }
            return RedirectToAction("Index", "Home");
        }

        [CustomAuthorize(AccessRightsInput = "011", Redirect = true)]
        public ActionResult Edit(int id)
        {
            User userDb = userService.GetAll(user => user.Id == id).FirstOrDefault();
            UserViewModel editViewModel = new UserViewModel();
            editViewModel.Id = userDb.Id;
            editViewModel.Name = userDb.Name;
            editViewModel.Password = userDb.Password;
            editViewModel.IsAdmin = userDb.IsAdmin;
            editViewModel.Phone = userDb.Phone;
            editViewModel.Email = userDb.Email;
            return View(editViewModel);
        }

        [CustomAuthorize(AccessRightsInput = "011")]
        [HttpPost]
        public ActionResult Edit(UserViewModel editViewModel)
        {
            if (userService.PreValidate())
            {
                User userInput = new DataAccess.Models.User();
                userInput.Id = editViewModel.Id;
                userInput.IsAdmin = editViewModel.IsAdmin;
                userInput.Name = editViewModel.Name;
                userInput.Phone = editViewModel.Phone;
                userInput.Email = editViewModel.Email;
                userInput.Password = editViewModel.Password;
                if (userService.Save(userInput))
                {
                    TempData["Message"] = "Edit made successfully!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Ooops something went wrong";
                }
                return RedirectToAction("Index", "Home");
            }
            return View(editViewModel);

        }

        [CustomAuthorize(AccessRightsInput = "011")]
        public ActionResult ChangePassword()
        {
            ChangePasswordViewModel changePasswordViewModel = new ChangePasswordViewModel();
            return View(changePasswordViewModel);
        }

        [CustomAuthorize(AccessRightsInput = "011")]
        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordViewModel changePasswordViewModel)
        {
            User userDb = userService.GetAll(user => user.Id == LoginUserSession.Current.UserId).FirstOrDefault();
            if (!userService.ChangePasswordValidation(userDb, changePasswordViewModel.OldPassword))
            {
                return View(changePasswordViewModel);
            }
            userDb.Password = changePasswordViewModel.NewPassword;
            if (userService.Save(userDb))
            {
                TempData["Message"] = "Password saved successfully!";
            }
            else
            {
                TempData["ErrorMessage"] = "Ooops something went wrong";
            }
            return RedirectToAction("Index", "Home");
        }

        [CustomAuthorize(AccessRightsInput = "001")]
        public ActionResult GetAll()
        {
            List<UserViewModel> usersViewModel = new List<UserViewModel>();
            foreach (User userDb in userService.GetAll())
            {
                usersViewModel.Add(new UserViewModel { Id = userDb.Id, Email = userDb.Email, Password = userDb.Password, Name = userDb.Name, Phone = userDb.Phone, IsAdmin = userDb.IsAdmin });
            }
            return View(usersViewModel);
        }

        [CustomAuthorize(AccessRightsInput = "001")]
        public ActionResult Delete(int id)
        {
            if (userService.DeleteById(id))
            {
                TempData["Message"] = "User deleted successfully!";
            }
            else
            {
                TempData["ErrorMessage"] = "Ooops something went wrong";
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

RushHour/Views/Shared/AccessDenied.cshtml
@using RushHour.Helpers
@{
    ViewBag.Title = "Access Denied";
    string path = Path.Combine(Constants.ImagesToolsDirectory, "access-denied.jpg");
}

<h2>Access Denied</h2>
<img src="@Url.Content(path)" alt="Access Denied" style="width:50%;height:50%" />

RushHour/Views/Shared/_InfoMessages.cshtml
@{
    if (string.IsNullOrEmpty(ViewBag.ErrorMessage) == false)
    {
        <h3>
            <span class="label label-danger">@ViewBag.ErrorMessage</span>
        </h3>
    }
    if (string.IsNullOrEmpty(ViewBag.Message) == false)
    {
        <h3>
            <span class="label label-success">@ViewBag.Message</span>
        </h3>
    }
    if (string.IsNullOrEmpty(Convert.ToString(TempData["Message"])) == false)
    {
        <h3>
            <span class="label label-success">@TempData["Message"]</span>
        </h3>
    }
    if (string.IsNullOrEmpty(Convert.ToString(TempData["ErrorMessage"])) == false)
    {
        <h3>
            <span class="label label-danger">@TempData["ErrorMessage"]</span>
        </h3>
    }
}

RushHour/Views/Shared/_Layout.cshtml
@using RushHour.Helpers;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Rush Hour</title>
    @*=====================================================================================================================================*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @*=====================================================================================================================================*@
    @*validation*@
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @*=====================================================================================================================================*@
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @*=====================================================================================================================================*@
    @*Boostrap 3 datepicker*@
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <link href="~/Content/bootstrap-datetimepicker.css" rel="stylesheet" />
    @*=====================================================================================================================================*@
    @*Datatables*@
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    @*=====================================================================================================================================*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home Page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @if (LoginUserSession.Current.IsAuthenticated)
                {
                    <div style="float:right;" class="navbar-brand">
                        <span style="color:blueviolet">Hello @LoginUserSession.Current.Name</span>
                    </div>
                    @Html.ActionLink("Logout", "Logout", "Home", new { area = "" }, new { @class = "navbar-brand" });
                    @Html.ActionLink("Edit Account", "Edit", "User", new { id = LoginUserSession.Current.UserId }, new { @class = "navbar-brand" });
                    @Html.ActionLink("Change Password", "ChangePassword", "User", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Appointments CRUD", "GetAll", "Appointment", new { area = "" }, new { @class = "navbar-brand" })
                    if (LoginUserSession.Current.IsAdmin)
                    {
                        @Html.ActionLink("Activites CRUD", "GetAll", "Activity", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Users CRUD", "GetAll", "User", new { area = "" }, new { @class = "navbar-brand" })
                    }
                }
                else
                {
                    @Html.ActionLink("Register", "Register", "User", new { area = "" }, new { @class = "navbar-brand" });
                    @Html.ActionLink("Login", "Login", "Home", new { area = "" }, new { @class = "navbar-brand" });
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @Html.Partial("_InfoMessages")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Rush Hour</p>
        </footer>
    </div>

</body>
</html>